version: "3.1"

services:
  nginx:
    image: rdesfo/fcc-projects
    volumes:
      - .:/usr/share/nginx/html:z
    ports:
      - "8080:80"
    security_opt:
      - label:type:docker_t
    secrets:
      - source: openweathermapappid
        target: openweather_secret
        uid: '100'
        gid: '101'
        mode: 0440

secrets:
 openweathermapappid:
   external: true
