version: "3.1"

services:
  nginx:
    image: rdesfo/fcc-projects
    volumes:
      - .:/usr/share/nginx/html:z
    ports:
      - "8080:80"
    secrets:
      - openweathermapappid

secrets:
 openweathermapappid:
   external: true
